project_id = "lxkstlsfxocaswqwlmed"

[functions.client-chat]
verify_jwt = false

[functions.send-alerts]
verify_jwt = false

[functions.verify-email-domain]
verify_jwt = false

[functions.register-email-domain]
verify_jwt = false

[functions.log-app-issue]
verify_jwt = false